# Generated by Django 3.1.1 on 2020-09-17 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('02', 'Ысык-Көл обл.'), ('03', 'Жалал-Абад обл.'), ('04', 'Нарын обл.'), ('05', 'Баткен обл.'), ('06', 'Ош обл.'), ('07', 'Талас обл.'), ('08', 'Чүй обл.'), ('11', 'Бишкек ш.'), ('21', 'Ош ш.')], max_length=2, verbose_name='region')),
                ('name', models.CharField(max_length=55, verbose_name='name')),
                ('gov_admin', models.CharField(max_length=255, verbose_name='Мам админстрация башчы (ААТ)')),
                ('stat_admin', models.CharField(max_length=255, verbose_name='Статистика башчы (ААТ)')),
                ('center', models.CharField(max_length=255, verbose_name='center of the district')),
                ('stat_address', models.CharField(max_length=255, verbose_name='stat address')),
                ('counter', models.CharField(default='000001', max_length=6)),
                ('number', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=45, verbose_name='last name')),
                ('first_name', models.CharField(max_length=45, verbose_name='first name')),
                ('patronymic', models.CharField(blank=True, max_length=45, null=True, verbose_name='patronymic')),
                ('birth_day', models.DateField(verbose_name='birth day')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('serial', models.CharField(choices=[('ID', 'ID'), ('AN', 'AN'), ('AC', 'AC')], default='ID', max_length=2, verbose_name='serial')),
                ('passport_number', models.CharField(max_length=7, unique=True, verbose_name='passport number')),
                ('PIN', models.CharField(max_length=14, unique=True, verbose_name='PIN')),
                ('photo', models.ImageField(upload_to='employee/photos', verbose_name='photo')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Coordinator'), (2, 'Instructor'), (3, 'Census Taker')], default=1, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='name')),
                ('code', models.CharField(max_length=14, unique=True, verbose_name='code')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.district')),
            ],
            options={
                'verbose_name': 'Territory',
                'verbose_name_plural': 'Territories',
                'ordering': ['code'],
            },
        ),
    ]
