# Generated by Django 3.1.1 on 2020-09-30 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['region'], 'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AddField(
            model_name='employee',
            name='agreement',
            field=models.CharField(default=0, max_length=6, verbose_name='келишим'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='users/qr-codes', verbose_name='QR код'),
        ),
        migrations.AlterField(
            model_name='district',
            name='number',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='id of the district'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.district', verbose_name='district'),
        ),
    ]
