# Generated by Django 3.1.1 on 2020-09-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_auto_20200930_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='agreement',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='келишим'),
        ),
    ]
