# Generated by Django 3.1.1 on 2020-10-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_auto_20200930_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Конфигурация', 'verbose_name_plural': 'Конфигурациялар'},
        ),
    ]
