# Generated by Django 3.1.1 on 2020-10-21 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0007_auto_20201001_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['region'], 'verbose_name': 'Район', 'verbose_name_plural': 'Райондор'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Кызматкер', 'verbose_name_plural': 'Кызматкерлер'},
        ),
        migrations.AlterModelOptions(
            name='territory',
            options={'ordering': ['code'], 'verbose_name': 'Аймак', 'verbose_name_plural': 'Аймактар'},
        ),
        migrations.AddField(
            model_name='employee',
            name='territory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='census.territory', verbose_name='aймак'),
        ),
        migrations.AlterField(
            model_name='district',
            name='center',
            field=models.CharField(max_length=255, verbose_name='райондун борбору'),
        ),
        migrations.AlterField(
            model_name='district',
            name='counter',
            field=models.CharField(default='000001', max_length=6, verbose_name='келишимдин саны'),
        ),
        migrations.AlterField(
            model_name='district',
            name='gov_admin',
            field=models.CharField(max_length=255, verbose_name='мам админстрация башчы (ААТ)'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=55, verbose_name='аты'),
        ),
        migrations.AlterField(
            model_name='district',
            name='number',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='райондун ID -си'),
        ),
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.CharField(choices=[('02', 'Ысык-Көл обл.'), ('03', 'Жалал-Абад обл.'), ('04', 'Нарын обл.'), ('05', 'Баткен обл.'), ('06', 'Ош обл.'), ('07', 'Талас обл.'), ('08', 'Чүй обл.'), ('11', 'Бишкек ш.'), ('21', 'Ош ш.')], max_length=2, verbose_name='область'),
        ),
        migrations.AlterField(
            model_name='district',
            name='stat_address',
            field=models.CharField(max_length=255, verbose_name='статистика бөлүмдүн дареги'),
        ),
        migrations.AlterField(
            model_name='district',
            name='stat_admin',
            field=models.CharField(max_length=255, verbose_name='статистика башчы (ААТ)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PIN',
            field=models.CharField(max_length=14, unique=True, verbose_name='ПИН'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=255, verbose_name='дарек'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_day',
            field=models.DateField(verbose_name='туулган күн'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=45, verbose_name='аты'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=45, verbose_name='фамилиясы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(max_length=7, unique=True, verbose_name='паспорт номери'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='атасынын аты'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='employee/photos', verbose_name='сүрөт'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='employee/qr-codes', verbose_name='QR код'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Координатор'), (2, 'Инструктор'), (3, 'Каттоочу')], default=1, verbose_name='ролу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='serial',
            field=models.CharField(choices=[('ID', 'ID'), ('AN', 'AN'), ('AC', 'AC')], default='ID', max_length=2, verbose_name='паспорт сериасы'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Координатор'), (2, 'Инструктор'), (3, 'Каттоочу')], default=1, verbose_name='ролу'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='code',
            field=models.CharField(max_length=14, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.district', verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='name',
            field=models.CharField(max_length=90, verbose_name='аты'),
        ),
    ]
