# Generated by Django 3.1.1 on 2020-10-27 07:32

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0008_auto_20201021_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-id'], 'verbose_name': 'Кызматкер', 'verbose_name_plural': 'Кызматкерлер'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=cropperjs.models.CropperImageField(upload_to='employee/photos', verbose_name='сүрөт'),
        ),
    ]
