# Generated by Django 3.1.1 on 2020-10-07 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0007_auto_20201001_1527'),
        ('accounts', '0003_auto_20201001_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='census.district', verbose_name='район'),
        ),
    ]
